# Generated by Django 4.2.16 on 2025-06-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_tag_alter_favorite_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
