# Generated by Django 4.2.16 on 2025-06-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_code',
            field=models.CharField(default='366d1f858d', max_length=10, unique=True),
        ),
    ]
