# Generated by Django 4.2.16 on 2025-06-13 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_shortlink_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
