# Generated by Django 4.2.16 on 2025-06-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_follow_unique_follow_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
